class TestContact():
    def test_hello(self):
        assert 1
    def test_hello1(self):
        assert 1
    def test_hello2(self):
        assert 1
    def test_hello3(self):
        assert 1
    def test_hello4(self):
        assert 1
    def test_hello5(self):
        assert 1
    def test_hello6(self):
        assert 1
    def test_hello7(self):
        assert 1
    def test_hello8(self):
        assert 1
    def test_hello9(self):
        assert 1
    def test_hello10(self):
        assert 1
    def test_hello11(self):
        assert 1
    def test_hello12(self):
        assert 1
    def test_hello13(self):
        assert 1
    def test_hello14(self):
        assert 1
    def test_hello15(self):
        assert 1

    def test_hello16(self):
            assert 0